version: '3.8'

services:
  # Building the Database building
  postgres-db:
    image: postgres:15-alpine
    container_name: ride-db-container
    environment:
      - POSTGRES_USER=kiran
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ride_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kiran -d ride_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Building the Ride Service building
  ride-service:
    build: . # Tells Docker to look for the 'Dockerfile' in the current folder
    container_name: ride-service-app
    depends_on:
      postgres-db:
        condition: service_healthy # Wait for the DB to be ready before starting Java
    environment:
      # These match the ${VARIABLE} names you wrote in application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ride_db
      - SPRING_DATASOURCE_USERNAME=kiran
      - SPRING_DATASOURCE_PASSWORD=pass
    ports:
      - "8080:8080"