version: '3.8'

services:
  # Building the Database building
  postgres-db:
    image: postgres:15-alpine
    container_name: ride-db-container
    environment:
      - POSTGRES_USER=kiran
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ride_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kiran -d ride_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis-cache:
    image: redis:7-alpine
    container_name: ride-redis-container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  rideshare-system-network:
    driver: bridge